# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/shakti/Coding/github/impulse-nn

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/shakti/Coding/github/impulse-nn

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/shakti/Coding/github/impulse-nn/CMakeFiles /home/shakti/Coding/github/impulse-nn/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/shakti/Coding/github/impulse-nn/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named impulse

# Build rule for target.
impulse: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 impulse
.PHONY : impulse

# fast build rule for target.
impulse/fast:
	$(MAKE) -f CMakeFiles/impulse.dir/build.make CMakeFiles/impulse.dir/build
.PHONY : impulse/fast

src/layer.o: src/layer.cpp.o

.PHONY : src/layer.o

# target to build an object file
src/layer.cpp.o:
	$(MAKE) -f CMakeFiles/impulse.dir/build.make CMakeFiles/impulse.dir/src/layer.cpp.o
.PHONY : src/layer.cpp.o

src/layer.i: src/layer.cpp.i

.PHONY : src/layer.i

# target to preprocess a source file
src/layer.cpp.i:
	$(MAKE) -f CMakeFiles/impulse.dir/build.make CMakeFiles/impulse.dir/src/layer.cpp.i
.PHONY : src/layer.cpp.i

src/layer.s: src/layer.cpp.s

.PHONY : src/layer.s

# target to generate assembly for a file
src/layer.cpp.s:
	$(MAKE) -f CMakeFiles/impulse.dir/build.make CMakeFiles/impulse.dir/src/layer.cpp.s
.PHONY : src/layer.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/impulse.dir/build.make CMakeFiles/impulse.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/impulse.dir/build.make CMakeFiles/impulse.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/impulse.dir/build.make CMakeFiles/impulse.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/matrix.o: src/matrix.cpp.o

.PHONY : src/matrix.o

# target to build an object file
src/matrix.cpp.o:
	$(MAKE) -f CMakeFiles/impulse.dir/build.make CMakeFiles/impulse.dir/src/matrix.cpp.o
.PHONY : src/matrix.cpp.o

src/matrix.i: src/matrix.cpp.i

.PHONY : src/matrix.i

# target to preprocess a source file
src/matrix.cpp.i:
	$(MAKE) -f CMakeFiles/impulse.dir/build.make CMakeFiles/impulse.dir/src/matrix.cpp.i
.PHONY : src/matrix.cpp.i

src/matrix.s: src/matrix.cpp.s

.PHONY : src/matrix.s

# target to generate assembly for a file
src/matrix.cpp.s:
	$(MAKE) -f CMakeFiles/impulse.dir/build.make CMakeFiles/impulse.dir/src/matrix.cpp.s
.PHONY : src/matrix.cpp.s

src/network.o: src/network.cpp.o

.PHONY : src/network.o

# target to build an object file
src/network.cpp.o:
	$(MAKE) -f CMakeFiles/impulse.dir/build.make CMakeFiles/impulse.dir/src/network.cpp.o
.PHONY : src/network.cpp.o

src/network.i: src/network.cpp.i

.PHONY : src/network.i

# target to preprocess a source file
src/network.cpp.i:
	$(MAKE) -f CMakeFiles/impulse.dir/build.make CMakeFiles/impulse.dir/src/network.cpp.i
.PHONY : src/network.cpp.i

src/network.s: src/network.cpp.s

.PHONY : src/network.s

# target to generate assembly for a file
src/network.cpp.s:
	$(MAKE) -f CMakeFiles/impulse.dir/build.make CMakeFiles/impulse.dir/src/network.cpp.s
.PHONY : src/network.cpp.s

src/neuron.o: src/neuron.cpp.o

.PHONY : src/neuron.o

# target to build an object file
src/neuron.cpp.o:
	$(MAKE) -f CMakeFiles/impulse.dir/build.make CMakeFiles/impulse.dir/src/neuron.cpp.o
.PHONY : src/neuron.cpp.o

src/neuron.i: src/neuron.cpp.i

.PHONY : src/neuron.i

# target to preprocess a source file
src/neuron.cpp.i:
	$(MAKE) -f CMakeFiles/impulse.dir/build.make CMakeFiles/impulse.dir/src/neuron.cpp.i
.PHONY : src/neuron.cpp.i

src/neuron.s: src/neuron.cpp.s

.PHONY : src/neuron.s

# target to generate assembly for a file
src/neuron.cpp.s:
	$(MAKE) -f CMakeFiles/impulse.dir/build.make CMakeFiles/impulse.dir/src/neuron.cpp.s
.PHONY : src/neuron.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... impulse"
	@echo "... edit_cache"
	@echo "... src/layer.o"
	@echo "... src/layer.i"
	@echo "... src/layer.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/matrix.o"
	@echo "... src/matrix.i"
	@echo "... src/matrix.s"
	@echo "... src/network.o"
	@echo "... src/network.i"
	@echo "... src/network.s"
	@echo "... src/neuron.o"
	@echo "... src/neuron.i"
	@echo "... src/neuron.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

